# Generated by Django 4.0.6 on 2022-07-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
